(ID "a")
(PUNCT "=")
(LIT "This is a rather long string containing\n    several lines of text much as you would do in C.")
(NEWLINE)
(LIT "This is a rather long string containing\n    several lines of text much as you would do in C.")
(NEWLINE)
(ENDMARKER)
